Repository AnatoliyCh/bot-get-by-link, pull requests merged in 2022-07, with the labels that each got.

#26 Closes issues and Refactoring all project
  Bot.GetByLink.Client.Telegram.Polling/ClientPolling.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/ChatInfoCommand.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/CommandInvoker.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/SendContentFromUrlCommand.cs
  Bot.GetByLink.Client.Telegram.Polling/Program.cs
  Bot.GetByLink.Common.Infrastructure/Configuration/BotConfiguration.cs
  Bot.GetByLink.Common.Infrastructure/Configuration/ClientsConfiguration.cs
  Bot.GetByLink.Common.Infrastructure/Configuration/ProxyConfiguration.cs
  Bot.GetByLink.Common.Infrastructure/Interfaces/Configuration/IBotConfiguration.cs
  Bot.GetByLink.Common.Infrastructure/Interfaces/Configuration/IClientConfiguration.cs
  Bot.GetByLink.Common.Infrastructure/Interfaces/Configuration/IProxyConfiguration.cs
  Bot.GetByLink.Common.Infrastructure/Interfaces/ICommandInvoker.cs
  Bot.GetByLink.Proxy.Reddit/AccessTokenReddit.cs
  Bot.GetByLink.Proxy.Reddit/ProxyReddit.cs
Labels: enhancement, refactoring

#28 New Command | Error Handling Update | Update solution folders
  Bot.GetByLink.Client.Telegram.Common/Bot.GetByLink.Client.Telegram.Common.csproj
  Bot.GetByLink.Client.Telegram.Common/Interfaces/IMessageContext.cs
  Bot.GetByLink.Client.Telegram.Common/Model/Message.cs
  Bot.GetByLink.Client.Telegram.Polling/Bot.GetByLink.Client.Telegram.Polling.csproj
  Bot.GetByLink.Client.Telegram.Polling/ClientPolling.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/ChatInfoCommand.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/CommandInvoker.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/SendContentFromUrlCommand.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/SendMessageCommand.cs
  Bot.GetByLink.Client.Telegram.Polling/Enums/CommandName.cs
  Bot.GetByLink.Client.Telegram.Polling/Program.cs
  Bot.GetByLink.Common.Infrastructure/Abstractions/ProxyService.cs
  Bot.GetByLink.Common.Infrastructure/Interfaces/Configuration/IClientConfiguration.cs
  Bot.GetByLink.Common.Infrastructure/Interfaces/Configuration/IProxyConfiguration.cs
  Bot.GetByLink.Common.Infrastructure/Interfaces/IMessageContext.cs
  Bot.GetByLink.Common.Infrastructure/Interfaces/IProxyService.cs
  Bot.GetByLink.Common.Infrastructure/Model/Configuration/BotConfiguration.cs
  Bot.GetByLink.Common.Infrastructure/Model/Configuration/Clients/ClientConfiguration.cs
  Bot.GetByLink.Common.Infrastructure/Model/Configuration/ClientsConfiguration.cs
  Bot.GetByLink.Common.Infrastructure/Model/Configuration/Proxy/RedditConfiguration.cs
  Bot.GetByLink.Common.Infrastructure/Model/Configuration/Proxy/VkConfiguration.cs
  Bot.GetByLink.Common.Infrastructure/Model/Configuration/ProxyConfiguration.cs
  Bot.GetByLink.Common.Infrastructure/Model/ProxyResponseContent.cs
  Bot.GetByLink.Proxy.Reddit/ProxyReddit.cs
  Bot.GetByLink.sln
Labels: enhancement, refactoring

#32 Telegram and console logging (polling client) | Extended LoggingBuilder
  .editorconfig
  Bot.GetByLink.Client.Telegram.Common/Bot.GetByLink.Client.Telegram.Common.csproj
  Bot.GetByLink.Client.Telegram.Common/Model/Logging/LoggingBuilderExtensions.cs
  Bot.GetByLink.Client.Telegram.Common/Model/Logging/TelegramLogger.cs
  Bot.GetByLink.Client.Telegram.Common/Model/Logging/TelegramLoggerProvider.cs
  Bot.GetByLink.Client.Telegram.Polling/Bot.GetByLink.Client.Telegram.Polling.csproj
  Bot.GetByLink.Client.Telegram.Polling/ClientPolling.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/CommandInvoker.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/SendMessageCommand.cs
  Bot.GetByLink.Client.Telegram.Polling/Program.cs
Labels: new function, refactoring

#33 Add IRegexWrapper | Refactoring
  Bot.GetByLink.Client.Telegram.Common/Bot.GetByLink.Client.Telegram.Common.csproj
  Bot.GetByLink.Client.Telegram.Common/Enums/CommandName.cs
  Bot.GetByLink.Client.Telegram.Common/Model/CommandRegexWrapper.cs
  Bot.GetByLink.Client.Telegram.Common/Model/Logging/TelegramLogger.cs
  Bot.GetByLink.Client.Telegram.Common/Model/UrlRegexWrapper.cs
  Bot.GetByLink.Client.Telegram.Polling/Bot.GetByLink.Client.Telegram.Polling.csproj
  Bot.GetByLink.Client.Telegram.Polling/ClientPolling.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/ChatInfoCommand.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/CommandInvoker.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/SendContentFromUrlCommand.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/SendMessageCommand.cs
  Bot.GetByLink.Client.Telegram.Polling/Program.cs
  Bot.GetByLink.Common.Infrastructure/Abstractions/Client.cs
  Bot.GetByLink.Common.Infrastructure/Abstractions/RegexWrapper.cs
  Bot.GetByLink.Common.Infrastructure/Bot.GetByLink.Common.Infrastructure.csproj
  Bot.GetByLink.Common.Infrastructure/Interfaces/IClient.cs
  Bot.GetByLink.Common.Infrastructure/Interfaces/ICommandInvoker.cs
  Bot.GetByLink.Common.Infrastructure/Interfaces/IRegexWrapper.cs
  Bot.GetByLink.Proxy.Reddit/ProxyReddit.cs
Labels: documentation, new function, refactoring

#27 Добавил форматирование сообщений | Add a function that formats the output
  Bot.GetByLink.Client.Telegram.Common/Interfaces/IFormatterContent.cs
  Bot.GetByLink.Client.Telegram.Common/Interfaces/IMessageContext.cs
  Bot.GetByLink.Client.Telegram.Common/Model/Message.cs
  Bot.GetByLink.Client.Telegram.Common/Model/ProxyResponseFormatter.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/CommandInvoker.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/SendContentFromUrlCommand.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/SendMessageCommand.cs
  Bot.GetByLink.Common.Infrastructure/Abstractions/ProxyService.cs
  Bot.GetByLink.Common.Infrastructure/Enums/MediaType.cs
  Bot.GetByLink.Common.Infrastructure/Interfaces/IMediaInfo.cs
  Bot.GetByLink.Common.Infrastructure/Interfaces/IProxyContent.cs
  Bot.GetByLink.Common.Infrastructure/Interfaces/IProxyService.cs
  Bot.GetByLink.Common.Infrastructure/Model/MediaInfo.cs
  Bot.GetByLink.Common.Infrastructure/Model/PictureRegexWrapper.cs
  Bot.GetByLink.Common.Infrastructure/Model/ProxyResponseContent.cs
  Bot.GetByLink.Proxy.Common/Bot.GetByLink.Proxy.Common.csproj
  Bot.GetByLink.Proxy.Common/ProxyHelper.cs
  Bot.GetByLink.Proxy.Reddit/Bot.GetByLink.Proxy.Reddit.csproj
  Bot.GetByLink.Proxy.Reddit/ProxyReddit.cs
  Bot.GetByLink.sln
Labels: documentation, refactoring, in progress

#34 Add new params in config
  Bot.GetByLink.Client.Telegram.Common/Model/ProxyResponseFormatter.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/CommandInvoker.cs
  Bot.GetByLink.Client.Telegram.Polling/appsettings.json
  Bot.GetByLink.Common.Infrastructure/Model/Configuration/Clients/ClientConfiguration.cs
  Bot.GetByLink.Common.Infrastructure/Model/ProxyResponseContent.cs
Labels: documentation, new function, refactoring

#36 Add Proxy VK | Refactoring
  Bot.GetByLink.Client.Telegram.Common/Interfaces/IFormatterContent.cs
  Bot.GetByLink.Client.Telegram.Common/Model/ProxyResponseFormatter.cs
  Bot.GetByLink.Client.Telegram.Polling/Bot.GetByLink.Client.Telegram.Polling.csproj
  Bot.GetByLink.Client.Telegram.Polling/Commands/SendContentFromUrlCommand.cs
  Bot.GetByLink.Client.Telegram.Polling/Commands/SendMessageCommand.cs
  Bot.GetByLink.Client.Telegram.Polling/Program.cs
  Bot.GetByLink.Client.Telegram.Polling/appsettings.json
  Bot.GetByLink.Common.Infrastructure/Abstractions/ProxyService.cs
  Bot.GetByLink.Common.Infrastructure/Interfaces/IProxyContent.cs
  Bot.GetByLink.Common.Infrastructure/Interfaces/IProxyService.cs
  Bot.GetByLink.Common.Infrastructure/Model/ProxyResponseContent.cs
  Bot.GetByLink.Proxy.Reddit/ProxyReddit.cs
  Bot.GetByLink.Proxy.Vk/Bot.GetByLink.Proxy.Vk.csproj
  Bot.GetByLink.Proxy.Vk/ProxyVK.cs
  Bot.GetByLink.Proxy.Vk/Regex/WallPostIdRegexWrapper.cs
  Bot.GetByLink.Proxy.Vk/Regex/WallRegexWrapper.cs
  Bot.GetByLink.Proxy.Vk/WellApi.cs
Labels: documentation, new function, refactoring
