Repository AnatoliyCh/bot-get-by-link, pull requests merged in 2022-08, with the labels that each got.

#42 Update of all documentation
  Documentation/NamingConvention/README.en.md
  Documentation/NamingConvention/README.ru.md
  Documentation/README.en.md
  Documentation/README.ru.md
  README.md
Labels: documentation

#51 Исправление названия параметра | Fix name parameter
  appsettings.json
Labels: bug

#56 Исправлено копирование файлов конфигурации | Fixed copying configuration files
  src/Bot.GetByLink.Client.Telegram.Polling/Bot.GetByLink.Client.Telegram.Polling.csproj
  src/Bot.GetByLink.Client.Telegram.WebHook/Bot.GetByLink.Client.Telegram.WebHook.csproj
Labels: bug

#57 Обновленное прокси ВК. Объекты: фото, альбомы, видео, документы | Updated proxy VK. Objects: photos, albums, videos, docs
  appsettings.json
  src/Bot.GetByLink.Client.Telegram.Common/Model/Commands/SendMessageCommand.cs
  src/Bot.GetByLink.Common.Enums/MediaType.cs
  src/Bot.GetByLink.Common.Infrastructure/Configuration/Clients/TelegramConfiguration.cs
  src/Bot.GetByLink.Common.Infrastructure/Configuration/Proxy/VkConfiguration.cs
  src/Bot.GetByLink.Common.Interfaces/Configuration/Clients/ITelegramConfiguration.cs
  src/Bot.GetByLink.Common.Interfaces/Configuration/Proxy/IVkConfiguration.cs
  src/Bot.GetByLink.Proxy.Vk/Abstractions/ContentReturnStrategy.cs
  src/Bot.GetByLink.Proxy.Vk/Interfaces/IContentReturnStrategy.cs
  src/Bot.GetByLink.Proxy.Vk/Model/MediaInfoExtra.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Regexs/IdResourceRegexWrapper.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Regexs/UrlAlbumRegexWrapper.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Regexs/UrlDocRegexWrapper.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Regexs/UrlPhotoRegexWrapper.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Regexs/UrlVideoRegexWrapper.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Regexs/UrlWallRegexWrapper.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Strategies/AlbumStrategy.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Strategies/DocStrategy.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Strategies/PhotoStrategy.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Strategies/VideoStrategy.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Strategies/WallStrategy.cs
  src/Bot.GetByLink.Proxy.Vk/ProxyVK.cs
  src/Bot.GetByLink.Proxy.Vk/Regexs/WallPostIdRegexWrapper.cs
  src/Bot.GetByLink.Proxy.Vk/Regexs/WallRegexWrapper.cs
  src/Bot.GetByLink.Proxy.Vk/WellApi.cs
Labels: documentation, new function, refactoring

#58 Добавлены гифки для вк и рефакторинг | Added GIFs for VK and refactoring
  appsettings.json
  src/Bot.GetByLink.Client.Telegram.Common/Model/Commands/SendContentFromUrlCommand.cs
  src/Bot.GetByLink.Client.Telegram.Common/Model/Commands/SendMessageCommand.cs
  src/Bot.GetByLink.Common.Infrastructure/Configuration/Clients/TelegramConfiguration.cs
  src/Bot.GetByLink.Common.Infrastructure/Configuration/Proxy/VkConfiguration.cs
  src/Bot.GetByLink.Proxy.Vk/Model/MediaInfoExtra.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Strategies/DocStrategy.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Strategies/VideoStrategy.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Strategies/WallStrategy.cs
Labels: new function, refactoring

#61 Обработчик клиентских исключений и рефакторинг | Client Exception Handler and Refactoring
  src/Bot.GetByLink.Client.Telegram.Common/Abstractions/TelegramClient.cs
  src/Bot.GetByLink.Client.Telegram.Common/Model/BuilderMessage.cs
  src/Bot.GetByLink.Client.Telegram.Common/Model/Commands/ChatInfoCommand.cs
  src/Bot.GetByLink.Client.Telegram.Common/Model/Commands/CommandInvoker.cs
  src/Bot.GetByLink.Client.Telegram.Common/Model/Commands/SendContentFromUrlCommand.cs
  src/Bot.GetByLink.Client.Telegram.Common/Model/Exceptions/ClientException.cs
  src/Bot.GetByLink.Client.Telegram.Common/Model/ProxyResponseFormatter.cs
  src/Bot.GetByLink.Common.Enums/ClientResource.cs
  src/Bot.GetByLink.Common.Enums/ExceptionType.cs
  src/Bot.GetByLink.Common.Infrastructure/Configuration/Clients/TelegramConfiguration.cs
  src/Bot.GetByLink.Common.Infrastructure/Configuration/Proxy/VkConfiguration.cs
  src/Bot.GetByLink.Common.Infrastructure/Exceptions/ClientException.cs
  src/Bot.GetByLink.Common.Infrastructure/Regexs/GifRegexWrapper.cs
  src/Bot.GetByLink.Common.Interfaces/IMessageContext.cs
  src/Bot.GetByLink.Common.Resources/Bot.GetByLink.Common.Resources.csproj
  src/Bot.GetByLink.Common.Resources/ClientResource.Designer.cs
  src/Bot.GetByLink.Common.Resources/ClientResource.resx
  src/Bot.GetByLink.Common.Resources/ResourceRepository.cs
  src/Bot.GetByLink.Proxy.Reddit/Regexs/RedditPostRegexWrapper.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Strategies/AlbumStrategy.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Strategies/DocStrategy.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Strategies/PhotoStrategy.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Strategies/VideoStrategy.cs
  src/Bot.GetByLink.Proxy.Vk/Model/Strategies/WallStrategy.cs
  src/Bot.GetByLink.Proxy.Vk/ProxyVK.cs
Labels: documentation, new function, refactoring

#62 Добавлена команда /help | Add /help command
  src/Bot.GetByLink.Client.Telegram.Common/Enums/CommandName.cs
  src/Bot.GetByLink.Client.Telegram.Common/Model/BuilderMessage.cs
  src/Bot.GetByLink.Client.Telegram.Common/Model/Commands/CommandInvoker.cs
  src/Bot.GetByLink.Client.Telegram.Common/Model/Commands/HelpCommand.cs
  src/Bot.GetByLink.Client.Telegram.Common/Model/Commands/SendContentFromUrlCommand.cs
  src/Bot.GetByLink.Client.Telegram.Common/Model/Commands/SendMessageCommand.cs
  src/Bot.GetByLink.Common.Enums/ClientResource.cs
  src/Bot.GetByLink.Common.Infrastructure/Configuration/Clients/TelegramConfiguration.cs
  src/Bot.GetByLink.Common.Infrastructure/Regexs/GifRegexWrapper.cs
  src/Bot.GetByLink.Common.Resources/ClientResource.Designer.cs
  src/Bot.GetByLink.Common.Resources/ClientResource.resx
  src/Bot.GetByLink.Common.Resources/ResourceRepository.cs
  src/Bot.GetByLink.Proxy.Reddit/ProxyReddit.cs
Labels: documentation, new function

#63 Обновление документации | Update documentation
  docs/README.en.md
  docs/README.ru.md
  src/Bot.GetByLink.Client.Telegram.Common/Model/Commands/CommandInvoker.cs
  src/Bot.GetByLink.Client.Telegram.Common/Model/Commands/HelpCommand.cs
  src/Bot.GetByLink.Common.Resources/ClientResource.Designer.cs
  src/Bot.GetByLink.Common.Resources/ClientResource.resx
  src/Bot.GetByLink.Proxy.Vk/Model/Regexs/UrlAlbumRegexWrapper.cs
Labels: documentation, refactoring

#64 Поддержка контейнера докер | Docker container support
  .dockerignore
  src/Bot.GetByLink.Client.Telegram.Common/Abstractions/TelegramClient.cs
  src/Bot.GetByLink.Client.Telegram.Common/Model/Commands/CommandInvoker.cs
  src/Bot.GetByLink.Client.Telegram.Common/Model/Commands/HelpCommand.cs
  src/Bot.GetByLink.Client.Telegram.Polling/Bot.GetByLink.Client.Telegram.Polling.csproj
  src/Bot.GetByLink.Client.Telegram.Polling/Dockerfile
  src/Bot.GetByLink.Client.Telegram.Polling/Properties/launchSettings.json
  src/Bot.GetByLink.Client.Telegram.WebHook/Bot.GetByLink.Client.Telegram.WebHook.csproj
  src/Bot.GetByLink.Client.Telegram.WebHook/Dockerfile
  src/Bot.GetByLink.Client.Telegram.WebHook/Properties/launchSettings.json
Labels: documentation, new function

#65 Добавлен новый параметр конфигурации ThrowPendingUpdates | Added new configuration option
  appsettings.json
  src/Bot.GetByLink.Client.Telegram.Common/Abstractions/TelegramClient.cs
  src/Bot.GetByLink.Client.Telegram.Common/Model/Logging/TelegramLogger.cs
  src/Bot.GetByLink.Common.Infrastructure/Configuration/Clients/TelegramConfiguration.cs
  src/Bot.GetByLink.Common.Interfaces/Configuration/Clients/ITelegramConfiguration.cs
Labels: documentation, new function, refactoring

#66 Игнорирование регистра для команд и команда /start | Case-ignoring commands and the /start command
  src/Bot.GetByLink.Client.Telegram.Common/Abstractions/TelegramClient.cs
  src/Bot.GetByLink.Client.Telegram.Common/Enums/CommandName.cs
  src/Bot.GetByLink.Client.Telegram.Common/Model/Commands/CommandInvoker.cs
Labels: new function, refactoring
